apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world-container
          image: robert076/hello-world-k8s:jik
          ports:
            - containerPort: 8080
