apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - name: api-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
